### ISSUE TITLE
PSES Preview doesn't load

### ISSUE THREAD

**Issue by corbob** [coc-extensions/coc-powershell#46]
### System Details

* _Vim or NeoVim?_: NeoVim
* _Version of Vim (run `vim --version`) or NeoVim_ (run `nvim --version`):  NVIM v0.4.0-1234-g1b99aa8c5 (a few days old nightly)

* _Version of `coc-powershell` (in Vim or NeoVim: `:CocList extensions coc-powershell`)_: 0.0.17 (local build with attempts to add `powershell/showHelp` command)
* _Operating System_: Windows 10 build 18922 (insiders build)
* _PowerShell version (in PowerShell: `$PSVersionTable`)_: 5.1.18922.1000

### Issue Description

Using downloadPSES.ps1 with the `-AllowPreRelease` flag. Getting the message: 
```
An error occurred while starting PowerShell Editor Services:

The argument is null. Provide a valid value for the argument, and then try running the command again.
   at System.Management.Automation.ValidateNotNullAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)


```

#### Expected Behaviour

Would expect PSIC to load without issue.

#### Actual Behaviour

Receiving error in attempting to load PSIC.

**Comment by TylerLeonhardt** [comment]
Ah... The Start-EditorServices.ps1 params might be different...

**Comment by TylerLeonhardt** [comment]
This is a relic of the past
