### ISSUE TITLE
Linting (Diagnostics) doesn't work

### ISSUE THREAD

**Issue by mikeTWC1984** [coc-extensions/coc-powershell#99]
### System Details

* _Vim or NeoVim?_: both
* _Version of Vim (run `vim --version`) or NeoVim_ (run `nvim --version`): Neovim 0.4.3
* _Version of `coc-powershell` : 0.1.1
* _Operating System_: linux
* _PowerShell version (in PowerShell: `$PSVersionTable`)_: 7

### Issue Description

I'm installing coc-extensions on the plain containers (various OS). Looks like there is some issue with linting for coc-powershell and coc-omnisharp. Initially I thought it's some global coc-nvim issue, because linting didn't work with python extension either. However after installing msft python server it was fixed. Then I realized linting is working with my old coc-powershell fork (I think it was v0.73). 
When I do CocInfo using latest coc-powershell/omnisharp I see additional output channel (cs and ps1). Using my old fork I only see one output channel (Powershell or omnisharp)
![image](https://user-images.githubusercontent.com/31977106/82398258-673e7980-9a20-11ea-8521-f9fe0bf63c48.png)

![image](https://user-images.githubusercontent.com/31977106/82398794-a6b99580-9a21-11ea-9f0d-3e736a01b2a4.png)

#### Expected Behaviour

![image](https://user-images.githubusercontent.com/31977106/82396888-1c6f3280-9a1d-11ea-9653-582910fb925e.png)

#### Actual Behaviour

-- Description of what actually happens --
![image](https://user-images.githubusercontent.com/31977106/82397166-cbac0980-9a1d-11ea-8ffa-642d37e7cb5e.png)

**Comment by TylerLeonhardt** [comment]
It looks like it's unable to find PSScriptAnalyzer... in the integrated console, can you run:

```
gmo -list PSScriptAnalyzer
```

**Comment by mikeTWC1984** [comment]
You are right, the command return nothing, and after installing PSScriptAnalyzer I see linting again. Thanks! Is it a bug or feature though? I guess coc-powershell used to install this module automatically

**Comment by TylerLeonhardt** [comment]
Hmm it should "just work" what's your `$env:PSModulePath` set to?

The last path should be a coc-powershell specific path and PSSA is supposed to be in that but I might have packaged it wrong.

**Comment by mikeTWC1984** [comment]
/root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules

**Comment by mikeTWC1984** [comment]
When I use the old fork I do see coc-powershell in PSModulePath indeed.

**Comment by TylerLeonhardt** [comment]
hmm and that's from within the PowerShell Integrated Console, yes?

**Comment by TylerLeonhardt** [comment]
On macOS, I have the correct path:
```
PS > $env:PSModulePath

  /Users/tyleonha/.local/share/powershell/Modules
:/usr/local/share/powershell/Modules
:/usr/local/microsoft/powershell/7/Modules
:/usr/local/Cellar/powershell-daily/7.1.0-daily.20200430/libexec/Modules
:/Users/tyleonha/.config/coc/extensions/node_modules/coc-powershell/PowerShellEditorServices
```

```
/Users/tyleonha/.config/coc/extensions/node_modules/coc-powershell/PowerShellEditorServices
```

**Comment by mikeTWC1984** [comment]
I just install everything again on the new linux machine, I do see coc-powershell/PowerShellEditorServices in the psmodulepath now, but linting is not working.  PSScriptAnalyzer is not in that folder. I do see it when I install my the old fork.

**Comment by mikeTWC1984** [comment]
This is what old extension has in this folder:
docs  Plaster  PowerShellEditorServices  PowerShellEditorServices.VSCode  PSScriptAnalyzer

The new one has only  PowerShellEditorServices

**Comment by mikeTWC1984** [comment]
OK, somehow 2.1.0 release does not contain those extra modules
https://github.com/PowerShell/PowerShellEditorServices/releases/tag/v2.1.0

**Comment by TylerLeonhardt** [comment]
Great find! I'll get that fixed

**Comment by TylerLeonhardt** [comment]
This should be fixed now :)
